name: Fraud Platform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Ici, on installe explicitement feast avec l'extension redis, flake8, pytest et apache-flink
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest apache-flink
        pip install "feast[redis]"

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Verify Feast Repository
      run: |
        cd src/feature_store/
        feast plan